//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public const int BOOKS = 1;

        public const int FLAVORS = 2;

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ItemId { get; set; }
        public byte ItemType { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
