//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IceCreamEntities : DbContext
    {
        public IceCreamEntities()
            : base("name=IceCreamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookCategory> BookCategories { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Flavor> Flavors { get; set; }
        public virtual DbSet<InputDetail> InputDetails { get; set; }
        public virtual DbSet<InputQuantity> InputQuantities { get; set; }
        public virtual DbSet<Input> Inputs { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Media> Medias { get; set; }
        public virtual DbSet<MembershipRegistration> MembershipRegistrations { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payout> Payouts { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
