//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InputDetail()
        {
            this.InputQuantities = new HashSet<InputQuantity>();
        }
    
        public int Id { get; set; }
        public int InputId { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Input Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputQuantity> InputQuantities { get; set; }

        public virtual ICollection<InputQuantity> InputQuantities1 { get; set; }

        public decimal GetTotalMoney()
        {
            return Price * Quantity;
        }
    }
}
