//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputQuantity
    {
        public int Id { get; set; }
        public int InputDetailId { get; set; }
        public int RemainQuantity { get; set; }
    
        public virtual InputDetail InputDetail { get; set; }
    }
}
