//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public double Discount { get; set; }
        public decimal InputMoney { get; set; }
        public string InputInformation { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }

        public decimal GetPriceAfterDiscount()
        {
            return Price - Price * (decimal)Discount / 100;
        }
    }
}
